[project]
name = "expectedmarketretrun"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "pandas-stubs==2.3.3.260113",
    "requests>=2.32.5",
    "yfinance>=1.1.0",
]
